apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sparkStreamingPvcName }}
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
